services:
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI= "mongodb+srv://baratam:t7S0pEzGgsgJehaw@nodeexample.i1glq.mongodb.net/"
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  database:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_URI= "mongodb+srv://baratam:t7S0pEzGgsgJehaw@nodeexample.i1glq.mongodb.net/"
    ports:
      - "27017:27017"
    
    
   
  
    
